<br /><br />
<div id="view-content">
	<p>View script for controller <b>User</b> and script/action name <b>add</b></p>
        
        
        <h1>test test test</h1>
        <button class="btn btn-danger" onclick="alert('AlexTours Welcoming U');">hey now brown cow</button>
        
        <div class="row">
            <div class="col-sm-4">
                <?php echo $this->form; ?>
            </div>
        </div>


</div>